# Generated by Django 2.2.12 on 2020-04-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('do_list', models.CharField(max_length=512)),
                ('did_list', models.CharField(max_length=512)),
                ('learnings', models.CharField(blank=True, max_length=1024, null=True)),
                ('free_writing', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
